lane :bonjour do
  UI.success "Bravo !"
  scan(
    project: "FastlaneFramework/FastlaneFramework.xcodeproj"
  )
  xcov

end

lane :deploy do
  if git_branch() == "master"
    version = get_version_number()
    print version
    set_github_release(
      repository_name:"PicoPark/fastlane-fram",
      name: version, #nom de la version à afficher sur github
      tag_name: "v#{version}",
      api_token: ENV["GITHUB_TOKEN"],
      description: changelog_from_git_commits(),
      commitish: "master"
    )
  end

end
